import test from 'node:test';import assert from 'node:assert/strict';import {WorldModel} from '../src/core/world-model.js';import {RETINA_RAYS} from '../src/core/constants.js';
const room={name:'test',width:60,height:40,ambientLight:.5,temperature:.5,spawn:{x:10,y:20,heading:0},objects:[{id:'w',kind:'wall',x:16,y:15,w:4,h:10},{id:'f',kind:'food',x:30,y:20,r:3,amount:.4,odor:1}]};
const drive={locomotorDrive:.8,coordinationDrive:.8,legs:[.8,.8,.8,.8,.8,.8],dna02Left:0,dna02Right:0,dna01Left:0,dna01Right:0,dng13Left:0,dng13Right:0,reverse:0,feed:0,drink:0,escape:0,halt:0,confidence:.7,conflict:0,turnEvidence:0,feedingEvidence:0,legLeft:.8,legRight:.8,centralArousal:0};
test('contact cannot privately select a reverse or turn program over a long horizon',()=>{const w=new WorldModel(room,1,'natural');w.setBrain(drive);const heading=w.fly.heading;let contactFrames=0;for(let i=0;i<3000;i++){w.step(.01);if(w.contactInput.some(value=>value>0))contactFrames++;}assert.equal(w.lastBehavior.state,'walk');assert.equal(w.lastBehavior.bias,0);assert(Math.abs(w.fly.heading-heading)<1e-12);assert(contactFrames>2500,'physical contact should remain available to the sensory boundary');const state=w.vnc.serialize().plant;for(const key of ['contactReverse','contactTurn','contactTurnTime','contactEscapeSign','contactSequence'])assert.equal(key in state,false,`${key} is a hidden plant-side behavior state`);});
test('identified reverse output can clear a frontal obstacle without a plant reflex',()=>{const w=new WorldModel(room,1,'natural');w.setBrain(drive);for(let i=0;i<180;i++)w.step(.01);const contactX=w.fly.x;w.setBrain({...drive,reverse:1});let sawReverse=false;for(let i=0;i<180;i++){w.step(.01);sawReverse||=w.lastBehavior.state==='reverse';}assert(sawReverse);assert(w.fly.x<contactX-2,'represented reverse output should move the body away from the wall');});
test('live room update preserves physiology, time, VNC state and depleted resource state',()=>{const w=new WorldModel(room,2,'natural');w.time=12.5;w.physiology.energy=.31;w.room.objects.find(o=>o.id==='f').amount=.12;const state=w.vnc.state,next=structuredClone(room);next.objects.push({id:'w2',kind:'wall',x:40,y:10,w:4,h:8});w.updateRoom(next);assert.equal(w.time,12.5);assert.equal(w.physiology.energy,.31);assert.equal(w.room.objects.find(o=>o.id==='f').amount,.12);assert.equal(w.vnc.state,state);assert(w.room.objects.some(o=>o.id==='w2'));});
test('world-to-brain sensory packet exposes no room coordinates',()=>{const w=new WorldModel(room,3),p=w.sense();assert.equal('x' in p,false);assert.equal('objects' in p,false);assert.equal('target' in p,false);assert.equal(p.retinaBrightness.length,RETINA_RAYS);});
test('food and water are visible but never misclassified as a blocking wall',()=>{const open={name:'open',width:80,height:50,ambientLight:.5,temperature:.5,spawn:{x:10,y:25,heading:0},objects:[{id:'f',kind:'food',x:18,y:25,r:3,amount:1,odor:1},{id:'a',kind:'water',x:26,y:25,r:3,amount:1,odor:1}]};const w=new WorldModel(open,4),p=w.sense();assert.equal(Math.max(...p.retinaProximity),0);});
test('airflow enters mechanosensation but never directly rotates the body',()=>{const w=new WorldModel(room,5),heading=w.fly.heading;w.airflow(1);w.setBrain({...drive,locomotorDrive:0,coordinationDrive:0,legs:[0,0,0,0,0,0],legLeft:0,legRight:0});w.step(.01);assert.equal(w.fly.heading,heading);const p=w.sense();assert(p.airflow[0]>0&&p.airflow[1]>0);});
test('same world seed and neural evidence produce the same trajectory',()=>{const a=new WorldModel(room,42,'natural'),b=new WorldModel(room,42,'natural');a.setBrain(drive);b.setBrain(drive);for(let i=0;i<1200;i++){a.step(.01);b.step(.01);}assert.deepEqual(a.fly,b.fly);assert.deepEqual(a.vnc.serialize(),b.vnc.serialize());});
test('an unseen nearby threat cannot alter physiology through privileged object coordinates',()=>{
  const base={name:'blind threat audit',width:80,height:50,ambientLight:.5,temperature:.5,spawn:{x:10,y:25,heading:0},objects:[]};
  const hidden={...base,objects:[{id:'t',kind:'threat',x:18,y:25,r:1,speed:0,heading:0,odor:1}]};
  const control=new WorldModel(base,73,'natural'),nearby=new WorldModel(hidden,73,'natural');
  control.setBrain(drive);nearby.setBrain(drive);
  // Do not call sense(): both individuals have received exactly the same
  // sensory/neural evidence and are too far apart for physical contact.
  control.step(.01);nearby.step(.01);
  assert.deepEqual(nearby.physiology.snapshot(),control.physiology.snapshot());
  assert.deepEqual(nearby.memory.serialize(),control.memory.serialize());
});
