import test from 'node:test';import assert from 'node:assert/strict';import {WorldModel} from '../src/core/world-model.js';import {RETINA_RAYS} from '../src/core/constants.js';
const room={name:'test',width:60,height:40,ambientLight:.5,temperature:.5,spawn:{x:10,y:20,heading:0},objects:[{id:'w',kind:'wall',x:16,y:15,w:4,h:10},{id:'f',kind:'food',x:30,y:20,r:3,amount:.4,odor:1}]};
const drive={forward:.8,reverse:0,turn:0,feed:0,drink:0,escape:0,halt:0,confidence:.7,centralArousal:.8,odorBias:0,odorPresence:0,visualBias:0,visualRisk:0,memoryBias:0,memoryConfidence:0,feedingEvidence:0};
test('contact is physical and the modeled VNC exits rather than bouncing forever',()=>{const w=new WorldModel(room,1,'natural');w.setBrain(drive);let sawReverse=false,sawSaccade=false;for(let i=0;i<900;i++){w.step(.01);sawReverse||=w.lastBehavior.state==='reverse';sawSaccade||=w.lastBehavior.state==='saccade';}assert(sawReverse);assert(sawSaccade);assert(w.fly.x<15.9||Math.abs(w.fly.y-20)>3,'fly should not remain pushing into the original contact point');});
test('live room update preserves physiology, time, VNC state and depleted resource state',()=>{const w=new WorldModel(room,2,'natural');w.time=12.5;w.physiology.energy=.31;w.room.objects.find(o=>o.id==='f').amount=.12;const state=w.vnc.state,next=structuredClone(room);next.objects.push({id:'w2',kind:'wall',x:40,y:10,w:4,h:8});w.updateRoom(next);assert.equal(w.time,12.5);assert.equal(w.physiology.energy,.31);assert.equal(w.room.objects.find(o=>o.id==='f').amount,.12);assert.equal(w.vnc.state,state);assert(w.room.objects.some(o=>o.id==='w2'));});
test('world-to-brain sensory packet exposes no room coordinates',()=>{const w=new WorldModel(room,3),p=w.sense();assert.equal('x' in p,false);assert.equal('objects' in p,false);assert.equal('target' in p,false);assert.equal(p.retinaBrightness.length,RETINA_RAYS);});
test('food and water are visible but never misclassified as a blocking wall',()=>{const open={name:'open',width:80,height:50,ambientLight:.5,temperature:.5,spawn:{x:10,y:25,heading:0},objects:[{id:'f',kind:'food',x:18,y:25,r:3,amount:1,odor:1},{id:'a',kind:'water',x:26,y:25,r:3,amount:1,odor:1}]};const w=new WorldModel(open,4),p=w.sense();assert.equal(Math.max(...p.retinaProximity),0);});
test('airflow enters mechanosensation but never directly rotates the body',()=>{const w=new WorldModel(room,5),heading=w.fly.heading;w.airflow(1);w.setBrain({...drive,forward:0,centralArousal:0});w.step(.01);assert.equal(w.fly.heading,heading);const p=w.sense();assert(p.airflow[0]>0&&p.airflow[1]>0);});
test('same world seed and neural evidence produce the same trajectory',()=>{const a=new WorldModel(room,42,'natural'),b=new WorldModel(room,42,'natural');a.setBrain(drive);b.setBrain(drive);for(let i=0;i<1200;i++){a.step(.01);b.step(.01);}assert.deepEqual(a.fly,b.fly);assert.deepEqual(a.vnc.serialize(),b.vnc.serialize());});
